name: Docker Maven Test with Allure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mantis-web-automation .

      - name: Run tests in Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            mantis-web-automation mvn clean test

      - name: Generate Allure Report
        if: always()
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            mantis-web-automation mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: allure-report
          path: ${{ github.workspace }}/target/site/allure-maven/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ${{ github.workspace }}/allure-report
